const { createClient } = require('@supabase/supabase-js');
const supabase = createClient(
  'https://prpcrwdsunjaxhcuvwqo.supabase.co',
  'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBycGNyd2RzdW5qYXhoY3V2d3FvIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc3Njg3MzgwNiwiZXhwIjoyMDkyNDQ5ODA2fQ.gRJEGrljtg2QKwIGFoSa1EpgObV4ihPtDLNRiS38sEg'
);

const drills = [
  // === FUNDAMENTALS (ALL POSITIONS) ===
  { name: 'Form Tackling', category: 'fundamentals', position_group: 'all', skill_focus: 'Tackling', difficulty: 'beginner', players_needed: 2, duration_minutes: 10, equipment: ['tackling dummy','cones'], description: 'Players approach a stationary dummy or partner. Break down: buzz feet, shoot hands to hips, drive through with legs. Wrap up and drive for 3 steps.', coaching_points: ['Eyes through the chest','Wrap and squeeze','Drive legs on contact','Head up — never lead with crown'], setup: 'Two lines facing each other, 5 yards apart. One line is ball carrier, other is tackler.', variations: ['Angle tackling','Open field','Sideline tackling'], tags: ['tackling','contact','safety'] },
  { name: 'Ball Security Gauntlet', category: 'fundamentals', position_group: 'all', skill_focus: 'Ball Security', difficulty: 'beginner', players_needed: 4, duration_minutes: 8, equipment: ['football','cones'], description: 'Ball carrier runs through a gauntlet of 4 defenders who try to strip the ball. Carrier must keep high and tight grip: fingers over tip, wrist locked, elbow tight, ball against chest.', coaching_points: ['High and tight','Cover the tip','Switch hands at midfield','Squeeze when hit'], setup: 'Set 4 cones 3 yards apart. Defenders stand at each cone. Carrier runs through.', variations: ['Add spin moves','Add obstacles','Blindside strip attempt'], tags: ['ball_security','fundamentals'] },
  { name: 'Stance & Start', category: 'fundamentals', position_group: 'all', skill_focus: 'Stance', difficulty: 'beginner', players_needed: 1, duration_minutes: 5, equipment: [], description: 'Proper 3-point and 2-point stance work. On whistle, fire out with first step. Emphasize weight distribution, back flat, eyes up.', coaching_points: ['Weight on balls of feet','Back flat, not rounded','Eyes up','Explosive first step'], setup: 'Players line up on a yard line.', variations: ['3-point','2-point','4-point for DL'], tags: ['stance','explosion','fundamentals'] },
  { name: 'Pursuit Angles', category: 'fundamentals', position_group: 'all', skill_focus: 'Pursuit', difficulty: 'intermediate', players_needed: 6, duration_minutes: 10, equipment: ['cones','football'], description: 'Teach players to take proper angles to the ball carrier. Coach stands at LOS with ball, points direction. All 6 defenders sprint to cutoff point, not directly at the ball.', coaching_points: ['Dont chase — cut off','Aim for where they WILL be','Full speed to the football','Break down in the last 3 yards'], setup: 'Defense lines up in base formation. Coach simulates ball carrier direction.', variations: ['Add actual ball carrier','Vary speeds','Sideline pursuit'], tags: ['pursuit','angles','team_defense'] },
  { name: 'Flag Pull Warm-Up', category: 'fundamentals', position_group: 'all', skill_focus: 'Agility', difficulty: 'beginner', players_needed: 2, duration_minutes: 5, equipment: ['flags','cones'], description: '1-on-1 in a 5x5 yard box. One player tries to pull the others flag belt. Teaches change of direction and closing speed.', coaching_points: ['Stay low','Reach for the hip','Mirror the ball carrier','Quick feet in the box'], setup: '5x5 yard box with cones.', variations: ['2v1','Add a spin move'], tags: ['warm_up','agility','fun'] },

  // === QB DRILLS ===
  { name: 'Drop & Throw', category: 'offense', position_group: 'qb', skill_focus: 'Passing Mechanics', difficulty: 'beginner', players_needed: 2, duration_minutes: 10, equipment: ['football','cones'], description: 'QB takes snap, executes 3-step or 5-step drop, sets feet, and throws to a stationary receiver at 10/15/20 yards. Focus on footwork and release point.', coaching_points: ['Eyes downfield during drop','Plant back foot','Step into throw','Follow through to target'], setup: 'QB at center spot. Receiver at 3 depth markers.', variations: ['3-step quick game','5-step intermediate','Rollout throws'], tags: ['passing','footwork','qb'] },
  { name: 'Handoff Mesh', category: 'offense', position_group: 'qb', skill_focus: 'Ball Handling', difficulty: 'beginner', players_needed: 2, duration_minutes: 8, equipment: ['football'], description: 'QB and RB practice the handoff mesh point. QB opens, seats the ball in RBs gut, RB clamps down. Work both sides.', coaching_points: ['QB: eyes on defense, not the ball','Seat the ball firmly','RB: both hands over the ball','Dont reach — let the mesh happen'], setup: 'QB under center, RB at depth.', variations: ['Add fake to other back','Play-action fake after','Under center and shotgun'], tags: ['handoff','mesh','ball_handling'] },
  { name: 'QB Rollout Drill', category: 'offense', position_group: 'qb', skill_focus: 'Mobility', difficulty: 'intermediate', players_needed: 3, duration_minutes: 10, equipment: ['football','cones'], description: 'QB rolls out to the right or left on the coachs call. Must set feet and throw to a receiver running a flat or out route. Emphasize throwing on the run.', coaching_points: ['Square shoulders to target','Dont throw across body','Plant outside foot','Keep eyes downfield while rolling'], setup: 'QB at center, 2 receivers running routes.', variations: ['Sprint out','Designed run vs throw read','Add a pass rusher'], tags: ['rollout','mobility','passing'] },
  { name: 'Read Progression', category: 'offense', position_group: 'qb', skill_focus: 'Decision Making', difficulty: 'advanced', players_needed: 5, duration_minutes: 12, equipment: ['football','cones'], description: 'QB drops back and reads 1st → 2nd → 3rd option. Coach holds up colored cards at each receiver — green means open, red means covered. QB must find the open man.', coaching_points: ['Dont stare at one receiver','Move eyes left to right','Throw to the first open man','If nobody open, scramble or throw away'], setup: '3 receivers at various depths. Coach with colored cards.', variations: ['Add rush','Half field reads','Red zone reads'], tags: ['reads','decision_making','advanced'] },

  // === RB DRILLS ===
  { name: 'Cut & Go', category: 'offense', position_group: 'rb', skill_focus: 'Vision & Cuts', difficulty: 'beginner', players_needed: 1, duration_minutes: 8, equipment: ['cones','football'], description: 'Set up 5 cones in a zigzag pattern 3 yards apart. RB runs through with ball, making sharp cuts at each cone. One cut and go — no dancing.', coaching_points: ['One cut — dont hesitate','Plant outside foot hard','Accelerate after the cut','Keep the ball in the outside arm'], setup: 'Zigzag cones, 3 yards apart.', variations: ['Add a defender at end','Mirror drill with partner','Speed cuts vs power cuts'], tags: ['cuts','vision','agility'] },
  { name: 'Hole Recognition', category: 'offense', position_group: 'rb', skill_focus: 'Vision', difficulty: 'intermediate', players_needed: 6, duration_minutes: 10, equipment: ['football','cones','blocking pads'], description: 'Set up 5 "linemen" (standing dummies or players) with varying gaps. RB takes handoff and must read which gap is open, then hit it full speed.', coaching_points: ['Read the blocks, not the defense','Press the hole before cutting','Dont bounce outside unless nothing inside','Follow your lead blocker'], setup: '5 players/dummies as OL with gaps. Coach opens/closes gaps randomly.', variations: ['Add a lead blocker','Zone vs gap reads','Add linebackers'], tags: ['vision','reads','running'] },
  { name: 'Pass Protection Pickup', category: 'offense', position_group: 'rb', skill_focus: 'Blocking', difficulty: 'intermediate', players_needed: 2, duration_minutes: 8, equipment: ['blocking pad'], description: 'RB sets up in pass pro. Coach or LB rushes from different angles. RB must identify the threat, get in position, and deliver a solid block.', coaching_points: ['Feet set before contact','Inside out technique','Punch and sustain','Dont lunge — stay balanced'], setup: 'RB at normal depth. Rusher comes from different angles.', variations: ['Blitz pickup left/right','Chip and release','Max protect'], tags: ['blocking','pass_pro','rb'] },

  // === WR DRILLS ===
  { name: 'Route Tree', category: 'offense', position_group: 'wr', skill_focus: 'Route Running', difficulty: 'beginner', players_needed: 2, duration_minutes: 12, equipment: ['football','cones'], description: 'WR runs each route on the basic tree: hitch, slant, out, in, corner, post, go, curl, comeback. QB throws on each route. 3 reps per route.', coaching_points: ['Sell the go route first','Sharp breaks — no rounding','Snap head around at the break','Catch with hands, not body'], setup: 'WR on sideline hash, QB at center.', variations: ['vs air','vs man coverage','Off the line press release'], tags: ['routes','catching','wr'] },
  { name: 'Releases Off the Line', category: 'offense', position_group: 'wr', skill_focus: 'Release Moves', difficulty: 'intermediate', players_needed: 2, duration_minutes: 8, equipment: ['cones'], description: 'WR works on beating press coverage. Practice: swim move, rip move, stutter-go, inside release, outside release. Defender gives light press.', coaching_points: ['Violent hands','Win in the first 2 steps','Dont let DB get hands on your chest','Attack the inside shoulder for outside release'], setup: 'WR and DB on LOS. 5 yard buffer zone.', variations: ['Full speed reps','Add route after release','Two-way go'], tags: ['release','press','technique'] },
  { name: 'Catch & Tuck', category: 'offense', position_group: 'wr', skill_focus: 'Catching', difficulty: 'beginner', players_needed: 2, duration_minutes: 8, equipment: ['football'], description: 'WR catches ball from various positions: high, low, over shoulder, across body. Immediately tuck and run 5 yards after every catch.', coaching_points: ['Hands form a diamond for high balls','Pinkies together for low balls','Look the ball in','Tuck and run — dont admire the catch'], setup: 'WR stands 10 yards from QB/coach.', variations: ['One-handed catches','Contested catches','Back shoulder'], tags: ['catching','hands','fundamentals'] },

  // === OL DRILLS ===
  { name: 'Fit & Drive', category: 'offense', position_group: 'ol', skill_focus: 'Run Blocking', difficulty: 'beginner', players_needed: 2, duration_minutes: 10, equipment: ['blocking sled','cones'], description: 'OL gets in proper fit position on sled or partner: hands inside, elbows tight, hips under shoulders. On whistle, drive for 5 yards with choppy steps.', coaching_points: ['Hands inside the chest plate','Elbows in — not chicken wings','Wide base, short steps','Drive through, not up'], setup: 'Sled or partner with pad.', variations: ['Double team','Combo to linebacker','Down block'], tags: ['blocking','drive','ol'] },
  { name: 'Pull & Kick', category: 'offense', position_group: 'ol', skill_focus: 'Pulling', difficulty: 'intermediate', players_needed: 3, duration_minutes: 10, equipment: ['cones','blocking pad'], description: 'Guard practices pull technique: open hip, sprint flat down LOS, turn upfield and kick out the end man. Must stay low through the turn.', coaching_points: ['First step: open hip, dont false step','Sprint flat — dont drift upfield too early','Eyes find the target','Deliver blow at POA, not before'], setup: 'Guard at normal position. DE dummy at end of LOS.', variations: ['Pull and lead through hole','Trap pull (short)','Long pull around end'], tags: ['pulling','technique','ol'] },
  { name: 'Pass Set Drill', category: 'offense', position_group: 'ol', skill_focus: 'Pass Protection', difficulty: 'intermediate', players_needed: 2, duration_minutes: 10, equipment: ['cones'], description: 'OL practices pass set: kick slide back, keep inside hand ready, mirror the rusher. Work against speed rush, bull rush, and spin move.', coaching_points: ['Dont cross feet','Keep inside hand active','Stay patient — dont lunge','Anchor on bull rush: drop hips, widen base'], setup: 'OL at LOS, DE/DT rusher with pad.', variations: ['Speed rush','Bull rush','Spin and counter'], tags: ['pass_pro','technique','ol'] },

  // === DL DRILLS ===
  { name: 'Get-Off Drill', category: 'defense', position_group: 'dl', skill_focus: 'Explosion', difficulty: 'beginner', players_needed: 1, duration_minutes: 8, equipment: ['cones'], description: 'DL in 3-point stance. On ball movement (coach simulates snap), explode out of stance low and fast. First step must be 6 inches, violent and forward.', coaching_points: ['React to the ball, not the sound','First step: 6 inches, low and fast','Hands punch simultaneously','Stay low through the charge'], setup: 'DL on LOS. Coach in front simulating snap.', variations: ['Add a blocker','React to run/pass key','Timed get-off'], tags: ['explosion','get_off','dl'] },
  { name: 'Swim & Rip', category: 'defense', position_group: 'dl', skill_focus: 'Pass Rush Moves', difficulty: 'intermediate', players_needed: 2, duration_minutes: 10, equipment: ['blocking pad'], description: 'DL practices two primary pass rush moves. Swim: arm over the top of blocker. Rip: arm under and through. Work both moves on both sides.', coaching_points: ['Set up the move with a jab step','Swim: reach over, pull their shoulder','Rip: violent upward motion under arm','Finish to the QB — dont stop after winning'], setup: 'DL vs OL with pad. 1-on-1.', variations: ['Add counter move','Spin off a failed swim','Bull to swim combo'], tags: ['pass_rush','technique','dl'] },
  { name: 'Shed & Tackle', category: 'defense', position_group: 'dl', skill_focus: 'Block Shedding', difficulty: 'intermediate', players_needed: 3, duration_minutes: 10, equipment: ['blocking pad','tackling dummy'], description: 'DL engages blocker, sheds the block using hands, then tackles the ball carrier behind. Teaches the full sequence: engage, shed, find ball, tackle.', coaching_points: ['Lock out arms on blocker','Rip or push/pull to shed','Find the ball immediately after shed','Break down and tackle'], setup: 'DL, blocker, and ball carrier. Ball carrier runs after DL engages blocker.', variations: ['Double team shed','Scoop and score after shed'], tags: ['block_shed','tackling','dl'] },

  // === LB DRILLS ===
  { name: 'Fill the Hole', category: 'defense', position_group: 'lb', skill_focus: 'Run Fits', difficulty: 'beginner', players_needed: 4, duration_minutes: 10, equipment: ['cones','football'], description: 'LB reads the RB flow, attacks the correct gap, and makes the tackle. Coach aligns dummies as OL with gaps. RB runs to a gap, LB must fill it.', coaching_points: ['Read the guards — they tell you where the play goes','Attack downhill, dont wait','Fill your gap before freelancing','Break down in the hole, dont overrun'], setup: '3 dummies as OL, RB behind them, LB at depth.', variations: ['Zone read look','Misdirection fake','Blitz fill'], tags: ['run_fits','gap_discipline','lb'] },
  { name: 'Drop & Cover', category: 'defense', position_group: 'lb', skill_focus: 'Pass Coverage', difficulty: 'intermediate', players_needed: 3, duration_minutes: 10, equipment: ['football','cones'], description: 'LB drops into zone on pass key. Must get to landmark (hook/curl zone) and find receivers entering the zone. React to QBs eyes and break on the ball.', coaching_points: ['Open hips, dont backpedal','Get depth to your landmark','Find receivers in your zone','Break on the QBs front shoulder'], setup: 'LB at depth. WR/TE running routes. QB throwing.', variations: ['Man coverage on RB','Hook/curl to flat','Spy technique'], tags: ['coverage','zone','lb'] },
  { name: 'Blitz Timing', category: 'defense', position_group: 'lb', skill_focus: 'Blitzing', difficulty: 'advanced', players_needed: 3, duration_minutes: 8, equipment: ['cones'], description: 'LB practices timing the snap count and hitting the gap at full speed. Must get to the QB before the ball is released. Work A-gap and B-gap blitzes.', coaching_points: ['Time the snap — be moving at the snap','Hit your gap, dont freelance','If QB escapes, redirect','Hands up when you get close'], setup: 'LB behind DL. QB simulating drop.', variations: ['Delayed blitz','Edge blitz','Zone blitz drop after showing blitz'], tags: ['blitz','pressure','lb'] },

  // === DB DRILLS ===
  { name: 'Backpedal & Break', category: 'defense', position_group: 'db', skill_focus: 'Footwork', difficulty: 'beginner', players_needed: 1, duration_minutes: 8, equipment: ['cones'], description: 'DB backpedals 10 yards. On coachs signal, breaks at 45 degrees left or right. Emphasize staying low, not popping up during the transition.', coaching_points: ['Stay on balls of feet','Dont cross feet in backpedal','Snap hips on the break','Accelerate out of the break'], setup: 'DB on yard line. Coach in front with hand signals.', variations: ['Break forward on underneath route','Speed turn on go route','Weave backpedal through cones'], tags: ['backpedal','footwork','db'] },
  { name: 'Ball Hawking', category: 'defense', position_group: 'db', skill_focus: 'Interceptions', difficulty: 'intermediate', players_needed: 2, duration_minutes: 10, equipment: ['football'], description: 'DB practices catching the football at the highest point. Coach throws balls from various angles — over shoulder, in front, tipped balls. DB must catch and tuck.', coaching_points: ['Track the ball, not the receiver','Catch at highest point','Tuck and return after INT','Yell BALL BALL BALL for teammates'], setup: 'DB at 15 yards. Coach throwing from QB depth.', variations: ['One-handed snags','Tipped ball drill','Jump ball contested'], tags: ['interceptions','ball_skills','db'] },
  { name: 'Press Coverage', category: 'defense', position_group: 'db', skill_focus: 'Man Coverage', difficulty: 'advanced', players_needed: 2, duration_minutes: 10, equipment: ['cones'], description: 'DB jams WR at the LOS (within 5 yards), then turns and runs with the receiver. Must disrupt timing without grabbing. Work inside and outside leverage.', coaching_points: ['Hands on chest plate — quick punch','Dont grab or hold','Mirror the WR hip','Stay in phase — dont panic and turn too early'], setup: 'DB and WR on LOS. QB throwing routes.', variations: ['Off coverage bail technique','Catch-man technique','Zone press bail'], tags: ['press','man_coverage','technique'] },

  // === CONDITIONING ===
  { name: 'Gassers', category: 'conditioning', position_group: 'all', skill_focus: 'Endurance', difficulty: 'intermediate', players_needed: 1, duration_minutes: 10, equipment: [], description: 'Sprint sideline to sideline (53 yards) and back. Thats 1 gasser. Rest 30 seconds between reps. Build up to 8-10 gassers per session.', coaching_points: ['Touch the line every time','Sprint through — dont slow down early','Control breathing on the rest','Compete against your last time'], setup: 'Full width of the field, sideline to sideline.', variations: ['Half gassers (to midfield)','Timed gassers','Position-specific counts'], tags: ['conditioning','endurance','running'] },
  { name: 'Bear Crawls', category: 'conditioning', position_group: 'all', skill_focus: 'Core Strength', difficulty: 'beginner', players_needed: 1, duration_minutes: 5, equipment: [], description: 'Hands and feet on the ground, butt low. Crawl forward 10 yards, then backwards 10 yards. Builds core, shoulder, and leg strength for contact.', coaching_points: ['Keep butt low — no hiking up','Opposite hand and foot move together','Stay controlled','Build speed as you get comfortable'], setup: '10 yard stretch of field.', variations: ['Lateral bear crawl','Bear crawl race','Bear crawl with resistance band'], tags: ['core','strength','conditioning'] },
  { name: 'Oklahoma Drill', category: 'conditioning', position_group: 'all', skill_focus: 'Toughness', difficulty: 'advanced', players_needed: 3, duration_minutes: 10, equipment: ['cones','football','blocking pad'], description: 'Classic 1-on-1 in a 3-yard wide lane. OL vs DL, then RB hits the hole. Teaches physicality, pad level, and will to win.', coaching_points: ['Pad level wins','Drive your feet on contact','RB: one cut and go','DL: hands inside, anchor and shed'], setup: '3-yard wide lane with cones. OL, DL, RB.', variations: ['2-on-2 version','Add a LB','Goal line version'], tags: ['contact','toughness','competition'] },

  // === AGILITY ===
  { name: 'Ladder Footwork', category: 'agility', position_group: 'all', skill_focus: 'Foot Speed', difficulty: 'beginner', players_needed: 1, duration_minutes: 8, equipment: ['agility ladder'], description: 'Various patterns through agility ladder: icky shuffle, in-in-out-out, lateral shuffles, single leg hops. Builds fast feet for all positions.', coaching_points: ['Quick feet — dont think, just move','Stay on balls of feet','Pump arms','Head up, not looking at feet'], setup: 'Agility ladder on flat ground.', variations: ['Forwards','Backwards','Lateral','Two ladders in sequence'], tags: ['agility','footwork','speed'] },
  { name: 'Cone Weave Sprint', category: 'agility', position_group: 'all', skill_focus: 'Change of Direction', difficulty: 'beginner', players_needed: 1, duration_minutes: 8, equipment: ['cones'], description: 'Set 5 cones 5 yards apart in a line. Sprint to first cone, plant and cut to the right, sprint to next, cut left. Finish with a 10-yard sprint.', coaching_points: ['Plant outside foot hard','Stay low through cuts','Explode out of each cut','Dont round the corners'], setup: '5 cones in a line, 5 yards apart.', variations: ['Timed runs','Add a ball','Race against partner'], tags: ['agility','speed','cuts'] },
  { name: 'Pro Agility (5-10-5)', category: 'agility', position_group: 'all', skill_focus: 'Lateral Quickness', difficulty: 'intermediate', players_needed: 1, duration_minutes: 8, equipment: ['cones'], description: 'Classic combine drill. Start at middle cone. Sprint 5 yards right, touch line. Sprint 10 yards left, touch line. Sprint 5 yards back to start. Test and build lateral speed.', coaching_points: ['Low start — explode out','Touch the line with near hand','Stay low on direction changes','Finish through the line'], setup: '3 cones 5 yards apart.', variations: ['Timed for evaluation','Add a ball catch at end','Backwards start'], tags: ['agility','testing','combine'] },

  // === TE DRILLS ===
  { name: 'Block & Release', category: 'offense', position_group: 'te', skill_focus: 'Dual Threat', difficulty: 'intermediate', players_needed: 3, duration_minutes: 10, equipment: ['football','blocking pad'], description: 'TE fires off the ball, delivers a 2-second block on DE, then releases into a route. Must sell the block before releasing. QB hits TE on the route.', coaching_points: ['Sell the block — 2 full seconds','Violent release off the block','Find open space in zone','Expect the ball immediately after release'], setup: 'TE on LOS next to OT. DE with pad. QB behind.', variations: ['Chip and release','Arc release','Seam route after block'], tags: ['blocking','receiving','te'] },
  { name: 'In-Line Blocking', category: 'offense', position_group: 'te', skill_focus: 'Run Blocking', difficulty: 'beginner', players_needed: 2, duration_minutes: 8, equipment: ['blocking pad'], description: 'TE works base block technique on DE. Must drive the DE off the ball or seal him inside depending on play call. Heavy emphasis on leverage.', coaching_points: ['Get your head on the play side','Drive through the defender','Sustain the block for 3 seconds','Finish — dont let go early'], setup: 'TE vs DE/pad on LOS.', variations: ['Down block','Reach block','Double team with OT'], tags: ['blocking','run_game','te'] },
];

drills.forEach((d, i) => d.sort_order = i + 1);

async function seed() {
  console.log(`Seeding ${drills.length} drills...`);
  const { data, error } = await supabase.from('training_drills').insert(drills).select('id, name');
  if (error) { console.error('Error:', error); return; }
  console.log(`✅ ${data.length} drills seeded successfully!`);
  
  const cats = {};
  drills.forEach(d => { cats[d.category] = (cats[d.category] || 0) + 1; });
  console.log('By category:', cats);
  
  const pos = {};
  drills.forEach(d => { pos[d.position_group] = (pos[d.position_group] || 0) + 1; });
  console.log('By position:', pos);
}

seed().catch(console.error);
